create project react
mburko/SecretShop_FE pull request #1
Opened 2022-04-06 17:40 UTC by nastiabroshko

2022-04-06 17:56 UTC, AlexheroUK approved these changes
![looksGood](https://user-images.githubusercontent.com/47336461/162038132-13904eda-537e-4e18-b543-fe4dd8eeacd5.gif)

2022-04-07 12:03 UTC, Magister25 approved these changes

2022-04-07 12:09 UTC, shevchenkoira approved these changes

2022-04-07 17:57 UTC, OleksiiDatsiuk requested changes
Delete/change default react logo images

2022-04-08 15:34 UTC, closed without merging